services:

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: dashboard
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend/dashboard-api
    depends_on:
      - postgres
    ports:
      - "5000:8080"

  frontend:
    build: 
      context: ./frontend/dashboard-client
    ports:
      - "80:80"

volumes:
  postgres_data: